FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BlogApp.sln", "./"]
COPY ["BlogData/BlogData.csproj", "BlogData/"]
COPY ["BlogApi/BlogApi.csproj", "BlogApi/"]
COPY ["BlogWeb/BlogWeb.csproj", "BlogWeb/"]
RUN dotnet restore
COPY . .
WORKDIR "/src/BlogApi"
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BlogApi.dll"]
